# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- azure*

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: docker version
  displayName: 'Show the Docker version'

- script: docker-compose version
  displayName: 'Show the Docker Compose version'

- script: env
  displayName: 'Dump environment variables'
