version: "3.2"

services:
  # Fire up the app to test, nginx_test
  nginx_test:
    image: nginx

  # Fire up hawkscan and scan the test app (nginx_test)
  hawkscan:
    image: stackhawk/hawkscan
    environment:
      API_KEY: "${HAWK_API_KEY}"
      APP_ID: "${APP_ID}"
      HOST: "${APP_HOST:-http://nginx_test}"
      ENV: "${APP_ENV:-Develop}"
    volumes:
      - type: bind
        source: .
        target: /hawk
    tty: true
    depends_on:
      - nginx_test
