version: 2.1

orbs:
  stackhawk: stackhawk/stackhawk@dev:alpha

workflows:
  scan-remote:
    jobs:
      - stackhawk/hawkscan-remote:
          app-id: 88d8c7dc-bd14-41e7-9e92-e87483871ea9
          env: "CircleCI"
          host: http://example.com

  scan-local:
    jobs:
      - stackhawk/hawkscan-local:
          host: http://nginx_test
          docker-network: scan_net
          app-id: 3d974920-42c5-4337-a9b7-fad5fc660100
          env: "CircleCI"
          steps:
            - run:
                name: Run Local Test Instance
                command: |
                  docker network create scan_net
                  docker run --rm --detach --network scan_net --name nginx_test nginx
