---
resources:
  - name: example-repo
    type: git
    icon: github-circle
    check_every: 15s
    source:
      uri: git@github.com:stackhawk/hawkscan-cicd-integrations
      branch: concourse
      private_key: ((ssh_private_key))

  - name: docker-compose
    type: docker-image
    icon: docker
    source:
      repository: karlkfi/concourse-dcind
      tag: latest

jobs:
  - name: hawkscan-local
    plan:
      - in_parallel:
          - get: example-repo
            trigger: true
          - get: docker-compose
      - task: scan-local
        privileged: true
        image: docker-compose
        config:
          platform: linux
          inputs:
            - name: example-repo
          params:
            API_KEY: ((hawk_api_key))
            APP_ID: 81368fba-b69d-4766-9994-cb27a3b5b238
            HOST: http://nginx_test
          run:
            path: entrypoint.sh
            args:
              - bash
              - -ceux
              - |
                cd example-repo
                docker-compose up --abort-on-container-exit
                docker-compose down
