---
resources:
  - name: example-repo
    type: git
    icon: github-circle
    check_every: 15s
    source:
      uri: git@github.com:stackhawk/hawkscan-cicd-integrations
      branch: concourse
      private_key: ((ssh_private_key))

  - name: stackhawk
    type: docker-image
    icon: eye
    source:
      repository: stackhawk/hawkscan
      tag: latest

jobs:
  - name: hawkscan-remote
    plan:
      - in_parallel:
          - get: example-repo
            trigger: true
          - get: stackhawk
      - task: scan-remote
        image: stackhawk
        config:
          platform: linux
          inputs:
            - name: example-repo
          params:
            API_KEY: ((hawk_api_key))
            REPO_DIR: /home/zap/example-repo
            APP_ID: a313a625-f4f0-4f04-800f-d7849a36a2bb
            HOST: http://example.com
          run:
            path: bash
            args:
              - -exc
              - |
                cp -rp example-repo "${REPO_DIR}"
                cd "${REPO_DIR}"
                shawk
