---
resources:
  - name: hawkscan-cicd-integrations
    type: git
    icon: github-circle
    check_every: 15s
    source:
      uri: git@github.com:stackhawk/hawkscan-cicd-integrations
      branch: concourse/initial-tests
      private_key: ((ssh_private_key))
  - name: stackhawk
    type: docker-image
    icon: docker
    source:
      repository: stackhawk/hawkscan
      tag: latest
  - name: docker-compose
    type: docker-image
    icon: docker
    source:
      repository: docker/compose
      tag: latest

jobs:
  - name: hawkscan-remote
    plan:
      - in_parallel:
          - get: hawkscan-cicd-integrations
            trigger: true
          - get: stackhawk
      - task: scan-remote
#        privileged: true
        image: stackhawk
        config:
          platform: linux
          inputs:
            - name: hawkscan-cicd-integrations
          params:
            API_KEY: ((hawk_api_key))
            REPO_DIR: /home/zap/hawk
            APP_ID: a313a625-f4f0-4f04-800f-d7849a36a2bb
            HOST: http://example.com
          run:
            path: bash
            args:
              - -exc
              - |
                mkdir /home/zap/hawk
                cp hawkscan-cicd-integrations/stackhawk.yml /home/zap/hawk
                cd /home/zap/hawk
                shawk

  - name: hawkscan-local
    plan:
      - in_parallel:
          - get: hawkscan-cicd-integrations
            trigger: true
          - get: docker-compose
      - task: scan-local
        privileged: true
        image: docker-compose
        config:
          platform: linux
          inputs:
            - name: hawkscan-cicd-integrations
          params:
            API_KEY: ((hawk_api_key))
            APP_ID: 81368fba-b69d-4766-9994-cb27a3b5b238
            HOST: http://nginx_test
          run:
            path: bash
            args:
              - -exc
              - |
                cp -rp hawkscan-cicd-integrations/ ./
                docker-compose up --abort-on-container-exit
