# Scan a local Docker container on a named bridge network
name: HawkScan Local Host

on:
  push:
    branches:
      - master
      - github/*
  pull_request:
    branches:
      - master

jobs:
  hawkscan:
    name: HawkScan
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Run Nginx
        run: docker run --rm --detach --publish 80:80 --name nginx_test nginx
      - name: Run HawkScan
        env:
          API_KEY: ${{secrets.HAWK_API_KEY}}
          APP_ID: 5b58fae0-2285-48dd-9e3a-ce9744f0e5ab
          HOST: http://localhost
        run: >
          docker run --volume $(pwd):/hawk --tty
          --network host
          --env API_KEY="${API_KEY}"
          --env APP_ID="${APP_ID}"
          --env HOST="${HOST}"
          stackhawk/hawkscan
